#!/usr/bin/env bash
# Entrypoint for the loadbalance-dns conformance fixture.
#
# 1. Writes the three pg-loadbalancetest entries to /etc/hosts (the file
#    is regenerated by docker on every container start, so we can't bake
#    these into the image at build time).
# 2. Boots three postgres clusters, each bound to a different loopback
#    address on port 5432.
# 3. Sleeps forever so the container stays up until docker stops it.
#
# Logging style mirrors the upstream PostgresNode harness: each cluster's
# postmaster log streams to its own file under /var/log/pg-lb/.

set -euo pipefail

PG_LB_ROOT="${PG_LB_ROOT:-/var/lib/pg-lb}"
LOG_ROOT=/var/log/pg-lb
mkdir -p "$LOG_ROOT"
chown -R postgres:postgres "$LOG_ROOT"

# /etc/hosts is owned by docker; we append rather than overwrite so the
# container's own short-hostname entry survives. Idempotent in case the
# entrypoint is re-run (docker exec). Note: we DO NOT use `sed -i` here
# because /etc/hosts is a docker bind-mount on most platforms and edits
# in place are unreliable across Docker engines.
if ! grep -q 'pg-loadbalancetest' /etc/hosts; then
  {
    echo '127.0.0.1 pg-loadbalancetest'
    echo '127.0.0.2 pg-loadbalancetest'
    echo '127.0.0.3 pg-loadbalancetest'
  } >> /etc/hosts
fi

# Start a cluster on a specific loopback IP. We append the listen_addresses
# via a one-shot postgresql.auto.conf (read-after-include semantics inside
# the cluster's data dir).
start_cluster () {
  local nodename=$1
  local ip=$2
  local data_dir="$PG_LB_ROOT/$nodename"
  local log_file="$LOG_ROOT/$nodename.log"

  # Set listen_addresses for this cluster.
  cat > "$data_dir/postgresql.auto.conf" <<EOF
listen_addresses = '$ip'
port = 5432
log_destination = 'stderr'
logging_collector = off
# Match upstream's connect_ok regex expectations: log every statement
# so the test can grep \`statement: SELECT 'connect{1,2,3,4}'\`.
log_statement = 'all'
log_line_prefix = '[$nodename] '
EOF
  chown postgres:postgres "$data_dir/postgresql.auto.conf"

  # Start in the background. -w waits for readiness so we don't race the
  # readiness probe further down.
  su postgres -c "pg_ctl -D '$data_dir' -l '$log_file' -w start"
}

start_cluster node1 127.0.0.1
start_cluster node2 127.0.0.2
start_cluster node3 127.0.0.3

# Stream all three logs to stdout so `docker logs` shows what the
# clusters are doing. tail -F follows files across rotation, although
# we configured logging_collector=off so they won't rotate here.
tail -F "$LOG_ROOT"/*.log &

# Forward SIGTERM/SIGINT to all postgres processes so the container
# shuts down cleanly when docker stops it.
on_term () {
  for nodename in node1 node2 node3; do
    su postgres -c "pg_ctl -D '$PG_LB_ROOT/$nodename' -m fast stop" || true
  done
  exit 0
}
trap on_term TERM INT

# Keep PID 1 alive. `wait` returns whenever a child exits; we re-enter
# the wait to keep the container alive past tail exits.
while true; do
  wait
done
