name: Report Workflow Stats

on:
  workflow_run:
    workflows:
      - Commitlint
      - PR to main branch
      - Publish to npm
    types: [completed]

permissions:
  contents: read

jobs:
  gh-workflow-stats:
    name: Github Workflow Stats
    runs-on: ubuntu-22.04
    permissions:
      actions: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Export GH Workflow Stats
        uses: neondatabase/gh-workflow-stats-action@e8595dc8961ed9ab05e33cb9b987b8a9fc1e1f83 # v0.1.4
        with:
          DB_URI: ${{ secrets.GH_REPORT_STATS_DB_RW_CONNSTR }}
          DB_TABLE: 'gh_workflow_stats_neonctl'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_RUN_ID: ${{ github.event.workflow_run.id }}
